db.url=jdbc:postgresql://localhost:5432/learnJava
db.username=learnJava
db.password=learnJava
db.pool.size=20
db.driver.class.name=org.postgresql.Driver
db.minimum.idle=2
db.connection.timeout=30000
liquibase.enabled=true
