# docker compose up
# docker compose down --volumes
version: '3.8'

services:

  learn-java-postgres:
    container_name: learn-java-postgres
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: learnJava
      POSTGRES_USER: learnJava
      POSTGRES_PASSWORD: learnJava
    ports:
      - 5432:5432
    volumes:
      - ./../docker/db/fill-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./../docker/db/pgdata/:/var/lib/postgresql/data/
