CREATE TABLE USER_LIMITS (
    USER_LIMITS_ID BIGSERIAL NOT NULL,
    USER_LIMITS_USER VARCHAR(32) NOT NULL UNIQUE,
    USER_LIMIT BIGINT NOT NULL,
    CONSTRAINT USER_LIMITS_pkey PRIMARY KEY (USER_LIMITS_ID)
);

CREATE TABLE USER_LIMITS_ROLLBACK (
    USER_LIMITS_ID BIGINT NOT NULL,
    USER_LIMIT BIGINT NOT NULL,
    CONSTRAINT USER_LIMITS_ROLLBACK_pkey PRIMARY KEY (USER_LIMITS_ID)
)

ALTER TABLE USER_LIMITS_ROLLBACK
    ADD CONSTRAINT fk_user_limits_rollback_id
    FOREIGN KEY (USER_LIMITS_ID) REFERENCES USER_LIMITS(USER_LIMITS_ID)
    ON DELETE CASCADE;